# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('instance_uuid', models.CharField(max_length=128)),
                ('period', models.IntegerField()),
                ('method', models.CharField(choices=[('max', 'max'), ('min', 'min'), ('avg', 'avg')], default='avg', max_length=3)),
                ('method_option', models.CharField(choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('=', '='), ('!=', '!=')], default='>=', max_length=2)),
                ('threshold', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_triggers', to='trigger.Item')),
            ],
        ),
    ]
