# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0002_auto_20161114_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='name',
        ),
    ]
