# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0003_auto_20161114_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='item',
            field=models.CharField(choices=[('disk write speed', 'disk write speed'), ('cpu usage', 'cpu usage'), ('incoming network traffic', 'incoming network traffic'), ('disk read speed', 'disk read speed'), ('memory usage', 'memory usage'), ('outgoing network traffic', 'outgoing network traffic')], max_length=32),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
