# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('trigger', '0004_auto_20161114_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='contacts',
            field=models.ManyToManyField(related_name='trigger', to='contact.Contact'),
        ),
    ]
