# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0005_trigger_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
