# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0006_trigger_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(False, False), (True, True)])),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trigger',
            name='method',
            field=models.CharField(choices=[('max', 'max'), ('avg', 'avg'), ('min', 'min')], default='avg', max_length=3),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='method_option',
            field=models.CharField(choices=[('!=', '!='), ('>=', '>='), ('<', '<'), ('=', '='), ('>', '>'), ('<=', '<=')], default='>=', max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trigger.Trigger'),
        ),
    ]
