# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceUUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.GenericIPAddressField()),
                ('register_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')])),
            ],
        ),
        migrations.AddField(
            model_name='instanceuuid',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances_uuid', to='heartbeat.MonitorAgent'),
        ),
    ]
