# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('action_time', models.CharField(max_length=32)),
                ('tel', models.CharField(max_length=32)),
                ('tel_status', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_status', models.BooleanField(default=True)),
            ],
        ),
    ]
